### ISSUE TITLE
Allow to specify the location of generated data base files

### ISSUE THREAD

**Issue by stworklog** [abdalmoniem/VSCode-C-Call-Hierarchy#2]
Currently "cscope.out" and "ctags.out" files are generated under the src folder or some root folder. I have to add both files in .gitignore to exclude them. It would be ideal if I can specify the location to be in "./.vscode" or any other folder.

**Comment by abdalmoniem** [comment]
good suggestion, will implement it shortly.

**Comment by abdalmoniem** [comment]
Fixed in Commit: 40820bc9ec560386611dab9050c7d5b18097d1dd and Release: [v2.1.3](https://github.com/abdalmoniem/VSCode-C-Call-Hierarchy/releases/v2.1.3)

Please give it a try and tell me your feedback
