### ISSUE TITLE
is it possible to use this in WSL?

### ISSUE THREAD

**Issue by exgs** [abdalmoniem/VSCode-C-Call-Hierarchy#4]
i open with workdirectory with vsc with wsl.(this means i can use command based on linux)
i also installed cscope, ctags and, readtags using this command apt-get install cscope universal-ctags.
and i build, file camed out cscope.out, ctags.out.
But, i can't see the visual extension hierarchy.
How can i solve this problem?

**Comment by exgs** [comment]
I also do different way to use this extension.
In window ,as you know, your extension recommanded to download cscope and ctags in local directory.
But, it doesn't work.
![image](https://user-images.githubusercontent.com/56223639/209061101-79ebfcad-1661-40b3-a8a0-485ab2d20109.png)
Only functions or variables selected with the "Show include Hierarchy" command are displayed.

**Comment by abdalmoniem** [comment]
Hi, the fact that there are results showing means that the required packages are installed and the extension is using them and working, but of you don't find any results that means that either you opened vscode workspace in a nested directory in your project or that cscope failed to build the correct database of the project, this is an issue with cscope, its not perfect and is scheduled to be replaced soon.
